### PR TITLE
[azure] Add method to set ContentDisposition

### PR DESCRIPTION
**Pull request by drnextgis**
So far we couldn't do that.

### CODE REVIEW

**Comment by jschneier** [comment]
Can you add something similar to [get_object_parameters](https://github.com/jschneier/django-storages/blob/1c6004cc68d8160ba51df1513810ef80251ad4c4/storages/backends/s3boto3.py#L502). Probably should have been a little smarter about the name so it would be consistent across backends...you could just call it `get_object_parameters`.

**Comment by drnextgis** [comment]
@jschneier thanks for the prompt reply. Done and rebased.

**Comment by drnextgis** [comment]
Hey, should I do something else to have it being merged?

**Comment by JeffreyCA** [comment]
Thank you for this! For future reference, the accepted key values for `AZURE_OBJECT_PARAMETERS` are: `content_type`, `content_encoding`, `content_language`, `content_disposition`, `cache_control`, and `content_md5`.

**Pull request merged**
