### PR TITLE
fix for files with size more than buffer size

### LINKED ISSUE #160: Problem with S3BotoStorageFile and a file greater than 5Mb
My team and I have found a problem in file-like interface for S3botoStorageFile.

If I do something like that:

```
 storage = S3BotoStorage()
 with storage.open("test.csv", "w") as f:
     df.to_csv(f)
```

where `df` is a Pandas' Dataframe, and file is greater than 5Mb, when we run the program from an ec2 instance, program stops over a write instruction.

Debugging we have seen that when file size become 5Mb the test in s3boto.py:159

```
if self.buffer_size <= self._buffer_file_size:
     self._flush_write_buffer()
```

is `True` for every write request, so for every write I have a request to upload to s3.... and after a few of seconds program freezes.

I think that test should be something like that

```
if (self._write_counter * self.buffer_size) <= self._buffer_file_size:
     self._flush_write_buffer()
```

Thank you.

### PR DESCRIPTION
**Pull request by vinayinvicible**
fixes #160

### CODE REVIEW

**Comment by vinayinvicible** [comment]
@jschneier can you take a look at this

**Comment by vinayinvicible** [comment]
@jschneier

**Comment by jschneier** [comment]
Thanks, will look at this today.

**Comment by vinayinvicible** [comment]
@jschneier 
any updates on this.

**Comment by jsh2134** [comment]
can this same change be ported to s3boto3.py ?

**Comment by jschneier** [comment]
Consolidated and fixed in #504.

**Pull request closed without merging**
