### PR TITLE
Avoid AWS_DEFAULT_ACL warning when overridden as a class variable

### PR DESCRIPTION
**Pull request by jdufresne**
Prevents warning spam to django-storages users that have overridden the insecure setting as a class variable.

### CODE REVIEW

**Comment by jschneier** [comment]
Not perfect but better than nothing I suppose.

**Comment by jdufresne** [comment]
@jschneier What do you think about a releasing 1.7.2 to include this fix? I run my project's tests with warnings enabled so avoiding this large amount of noise would be nice.

**Comment by davepeck** [comment]
I ran across this issue with a client who was explicitly overriding `default_acl` in a class variable anyway; I have to say that the warning was very confusing! To make sense of it, I eventually spelunked into `s3boto3.py` and did a `git blame`, which led me here.

@jschneier Is there any reason we shouldn't issue a 1.7.2 release that contains this fix?

**Comment by jschneier** [comment]
Sorry all I’ve started a new job recently and things have fallen behind.
Going to release a new version this weekend.

**Comment by jschneier** [comment]
@davepeck this has now been released, sorry for the delay.

**Comment by davepeck** [comment]
@jschneier Wow — thanks!

**Pull request merged**
