### PR TITLE
Dropbox 8.x support

### LINKED ISSUE #396: using Dropbox 8.1 MetaData is not subscriptable
https://github.com/jschneier/django-storages/blob/adefe324be22843148b03a2068d2922eaae1a48b/storages/backends/dropbox.py#L82

using python3.5 and dropbox 8.1 I have got the following error:

```
  File "/home/server/env/lib/python3.5/site-packages/storages/backends/dropbox.py", line 79, in listdir
    for entry in metadata['contents']:
TypeError: 'FolderMetadata' object is not subscriptable
```

if I open the source code of dropbox I can see that the class MetaData is not defining a __getitem__ method which is why this code is failing...

thanks and good job with this package

### PR DESCRIPTION
**Pull request by danni**
Fixes support for recent versions of the Dropbox SDK.

The API was radically different to the previous SDK, but the mocks used in the unit tests made it so the unit tests appeared to continue passing. This updates the backend to use the return types in the new SDK.

Fixes #396 and #397.

### CODE REVIEW

**Comment by patroqueeet** [comment]
@jschneier when will this be merged and released?

**Comment by zuck** [comment]
@jschneier Please, merge this PR. I currently have 6 apps in production blocked by this issue...

**Comment by 4levels** [comment]
Same here, please merge this as Dropbox deprecated the old API for Business accounts

**Comment by sww314** [comment]
@danni Can you resolve conflicts?

**Comment by danni** [comment]
I don't have a project running on this backend any more. I won't be able to test the result. Is someone else able to merge it?

**Comment by sww314** [comment]
@4levels or @zuck can your verify this fix? None of the maintainers are currently using the Dropbox integration. If the conflicts are fixed and someone will integration test, we can get it merged.

**Comment by 4levels** [comment]
Hi @sww314,

I'd love to but I'm in no position to do so since my Python skills are very limited.
I also don't understand the merge conflicts listed here, all changes in this PR seem very straightforward.

So far I've managed to get around this by creating a new class as extension, called `DropBoxTeamStorage` - I needed this anyway since the current DropBoxStorage class cannot handle the extra headers required for Dropbox Team accounts.  I then override the listdir method in the new class, making use of the newer Dropbox API response types so I'm not blocked.

PS. I'm curerntly creating a new PR to implement the DropBoxTeam solution I'm using.

Kind regards,

**Comment by matburnham** [comment]
I can confirm that this seems to work insofar as I can do a `listdir` which was failing before (#567). I'm not particularly au-fait with git, but have done as much as I can to figure out the merge conflicts.

I could possibly put together another commit to resolve them but I'm not sure I'll then be able to push it anywhere.

- `requirements-tests.txt` _appears_ to be new so I don't understand why it is conflicting?
- `test/test_dropbox.py` has mostly minor changes - only two appear to be significant but I don't know how to properly run this test and/or interpret the results
- `tox.ini` appears to be irrelevant whitespace changes; the only thing significant is pinning `dropbox` and some other libraries to a particular version; they weren't there before, they can probably be ignored.

If someone can point me to somewhere I can understand about how the tests are supposed to work I can try and figure that out.

**Comment by jschneier** [comment]
Ended up merging #724. Thanks.

**Pull request closed without merging**
