### PR TITLE
gcloud: Use DEFAULT_RETRY when uploading a file.

### PR DESCRIPTION
**Pull request by Hatell**
Use a default retry policy when uploading a file to Google Storage.

### CODE REVIEW

**Comment by jschneier** [comment]
What motivates this change?

**Comment by Hatell** [comment]
Recently I have had issues with Google Cloud Storage. Some times I got 503 and I had few data losses. GCS documentation says that when server answer 503 you need retry and use retry policy to automate it.

The default retry policy of `upload_from_file` is DEFAULT_RETRY_IF_GENERATION_SPECIFIED and call of `upload_from_file` doesn't specify generation so there is no retry.

**Comment by jschneier** [comment]
Okay, this change looks fine if you fix CI. Will need a rebase.

**Comment by Hatell** [comment]
Rebase is now done.

**Comment by jschneier** [comment]
Thanks, can you please fix the tests.

**Comment by Hatell** [comment]
Now tests are fixed.

**Comment by Hatell** [comment]
I fixed those flake8 issues.

**Comment by jschneier** [comment]
@Hatell what do you think about adding `retry=DEFAULT_RETRY` to `.delete()`? I think that's now the only place where there are no retries left.

For whatever reason it looks like the client lib uses `DEFAULT_RETRY` for all readonly operations and `DEFAULT_RETRY_IF_GENERATION_SPECIFIED` for all write/delete operations.

**Comment by Hatell** [comment]
I think that adding retry to delete is good idea. Can you do that now? I can do it tomorrow.

**Comment by jschneier** [comment]
Not sure if I have permissions to push to your branch, will let you do it.

**Comment by Hatell** [comment]
Retry is added to delete_blob call.

**Pull request merged**
