### PR TITLE
Support of latest azure_storage(>=0.33) added

### PR DESCRIPTION
**Pull request by exploreshaifali**

### CODE REVIEW

**Comment by aleccool213** [comment]
+1

**Comment by k0nG** [comment]
Just as a note for anyone like me who is having trouble getting the current azure storage backend to work with the Azure sdk. I've got it working with version `1.0.3`: https://github.com/Azure/azure-sdk-for-python/tree/v1.0.3

**Comment by sww314** [comment]
Possible duplicate of #170

**Comment by sww314** [comment]
Fixed in #565

**Pull request closed without merging**
