### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2 support is nearing end of life. At the end of this year, it will no longer be supported, including for security issues.
    
Django has already dropped support for Python 2 in Django 2.0. Follow upstream to be more compatible with the master branch as tests now pass.
    
For more details, see https://pythonclock.org/
    
All code changes and clean ups that were noticed were done. Changes include:
    
- Remove str/unicode compatibility shims.
- Remove encoding cookies from source files. Python 3 interprets all files as utf-8 by default.
- Remove unnecessary `__future__` imports. The features are now built-in.
- Use modern and simpler `super()` syntax.
- Update the wheel configuration to reflect it is no longer universal.
- Update trove classifiers.
- And more …
    
Also remove supported for end of life Python 3.4. It went end of life 2019-03-18.

### CODE REVIEW

**Comment by jdufresne** [comment]
I have rebased to resolve merge conflicts.

@jschneier What do you think about this change? It would be nice to get the project compatible with the Django master branch again.

**Comment by jdufresne** [comment]
Another reason this would be nice, Django 3.0 deprecated `forct_text()` in favor of `force_str()`. Using django-storages with Django 3.0 writes lots of deprecation warnings the consoles:

```
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
```

By moving to Python3-only, we can safely use `force_str()` or `str()`.

**Comment by debdolph** [comment]
Any progress on this?

**Comment by jdufresne** [comment]
Now that Python 2.7 is end-of-life and no longer receiving security updates, maybe now is the time? FWIW, here are the download statistics for django-storages for the last month. These where gathered using pypinfo:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  39.35% |        246,135 |
| 3.7            |  31.29% |        195,718 |
| 2.7            |  18.60% |        116,308 |
| 3.5            |   5.42% |         33,898 |
| 3.8            |   4.87% |         30,483 |
| 3.4            |   0.46% |          2,907 |
| 3.9            |   0.00% |             12 |
| 2.6            |   0.00% |              5 |
| Total          |         |        625,466 |


Python 2.7 is less than 20% of all downloads.

**Comment by jschneier** [comment]
@jdufresne I would like to drop Python 2 support this weekend. At minimum I would like to release a version with the features in master. I think I would also be remiss not to enforce the security updates on Python 2 as well.

Then another bump for the dropping.

**Comment by jdufresne** [comment]
:tada: Sounds like a good plan to me. Let me know if you need any PR rebased or other work done to assist in the effort.

Thanks for maintaining such an important project!

**Comment by jdufresne** [comment]
Hi @jschneier, hope you're doing well.

What do you think about moving ahead with the outlined plan above to release the next versions of django-storages? It has now been a month. It would be great to get the Django deprecation messages cleaned up. Let me know if there is anything I can do to help: changes, rebase, new fixes, or anything else. Cheers.

**Comment by jdufresne** [comment]
Hi @jschneier What do you think about moving ahead with the plan outlined in [March](https://github.com/jschneier/django-storages/pull/709#issuecomment-598554219). It would be really great to get rid of the emitted deprecation warnings.

Please let me know if I can help out in anyway. Either with this PR or with the release.

Here are the latest statistics from pypinfo. It shows a drop in the use of Python 2 as a percentage of downloads, now just 12.00%.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  35.79% |        372,748 |
| 3.7            |  30.90% |        321,836 |
| 3.8            |  14.18% |        147,632 |
| 2.7            |  12.00% |        125,003 |
| 3.5            |   6.44% |         67,111 |
| 3.4            |   0.68% |          7,088 |
| 3.9            |   0.00% |             51 |
| 3.3            |   0.00% |              9 |
| 2.6            |   0.00% |              3 |
| Total          |         |      1,041,481 |

**Comment by WhyNotHugo** [comment]
FWIW, users of Python2 can just use an older version of the library.

They're already forced  to used old versions of pretty much everything else, including Django.

I don't feel like they'd really be affected by this library dropping support for them.

**Comment by jschneier** [comment]
Let's do it.

**Pull request merged**
