### PR TITLE
Add local storage class with file overwriting capabilities

### LINKED ISSUE #1208: Local storage class with file overwrite
Hi @jschneier, I'd like to propose a companion [local storage class](https://gist.github.com/niccolomineo/2b034f97571ec8106ea41248b4e5156e) mimicking the `*_OVERWRITE_FILES` behavior for remote storages.

Would you accept a PR with such an addition?

### PR DESCRIPTION
**Pull request by niccolomineo**
Closes #1208

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
@jschneier can you take a look at this PR, please?

**Review by craigds — CHANGES_REQUESTED** [review]
(i'm not a maintainer of this project, but)

There's a more efficient implementation of this - instead of calling delete(), just override `OS_OPEN_FLAGS`, and tell `get_available_name` to just return the original name as-is.

```
    # Don't throw errors if the file already exists when saving.
    # https://manpages.debian.org/bullseye/manpages-dev/open.2.en.html#O_EXCL
    OS_OPEN_FLAGS = FileSystemStorage.OS_OPEN_FLAGS & ~os.O_EXCL
```

**Comment by niccolomineo** [comment]
> (i'm not a maintainer of this project, but)
> 
> There's a more efficient implementation of this - instead of calling delete(), just override `OS_OPEN_FLAGS`, and tell `get_available_name` to just return the original name as-is.
> 
> ```
>     # Don't throw errors if the file already exists when saving.
>     # https://manpages.debian.org/bullseye/manpages-dev/open.2.en.html#O_EXCL
>     OS_OPEN_FLAGS = FileSystemStorage.OS_OPEN_FLAGS & ~os.O_EXCL
> ```

I would avoid this: you're changing the class behaviour from outside.

**Comment by jschneier** [comment]
I think this should be a request to upstream can you open a ticket on the tracker? In general I think I would fix this by overriding `FileSystemStorage`.

**Comment by craigds** [comment]
'upstream': django?

> I would definitely avoid this, as you're changing / controlling the class behaviour from outside.

i wasn't suggesting monkeypatching anything - `OS_OPEN_FLAGS` is an attribute on Django's FileSystemStorage which can be overridden by the django-storages subclass.

**Comment by jschneier** [comment]
Yes opening a ticket on Django.

**Pull request closed without merging**
