### PR TITLE
Added error handling at import django.utils.six module. #758

### LINKED ISSUE #758: Support django 3.0
I tried django-storages 1.7.2 with [Django 3.0a1](https://pypi.org/project/Django/3.0a1/).
I found that django-storage uses the _**django.utils.six**_ module which [will be removed in django 3.0](https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis).

> django.utils.six - Remove usage of this vendored library or switch to [six](https://pypi.org/project/six/).

The module was used in the following places:
- storages
  - backends
    - s3boto3.py
    - apache_libcloud.py
    - sftpstorage.py
    - ftp.py
- tests
  - test_s3boto.py
  - test_s3boto3.py

### PR DESCRIPTION
**Pull request by yukihira1992**
I fixed #758.
If django-storages ends support for Python2, close this.

### CODE REVIEW

**Comment by jschneier** [comment]
Thanks for this, I'm not quite sure why they removed `six` before 1.11 is no longer supported. I think a better way to solve this is to do `try` `except` rather than depending on `six`.

Want to take a crack at that?

**Comment by yukihira1992** [comment]
Removed `six` and added error handling.

**Comment by jdufresne** [comment]
I think it would be overall simpler maintenance to follow Django's lead and drop support for Python 2. It is very close to EOL anyway. It will required fewer compatibility shims and workarounds. Work for this has started #709

**Comment by codingjoe** [comment]
Thanks for addressing this issue. I guess it blocked some people from testing the Django alpha.

> Thanks for this, I'm not quite sure why they removed `six` before 1.11 is no longer supported. I think a better way to solve this is to do `try` `except` rather than depending on `six`.

@jschneier I understand the confusion, yet `six` has undergone the regular deprecation cycle, which wasn't required, considering that it was never part of the official Django API.

> I think it would be overall simpler maintenance to follow Django's lead and drop support for Python 2. It is very close to EOL anyway. It will required fewer compatibility shims and workarounds. Work for this has started #709

@jdufresne I second that. I believe there is no need to wait until 1.11 hits EOL in April, since 1.11 extended support does not cover Python 2.7 since it's EOL is in December. So one should only use Django 1.11 on Python 3 after December.

It's absolutely admirable to keep support Python 2 for that long, but I guess it's time for django-storages v2.0.0 ;)

**Comment by jschneier** [comment]
This library saw such a dearth of development for such a long time that I am attempting to put in all the minimum necessary features before doing something drastic and breaking backwards combat too string. When I release 2.0 I think we will also move to strict semantic versioning - given where we started I found it impractical to start there. I understand the EOL timeline, however.

**Comment by codingjoe** [comment]
@jschneier I hear you. If you need any help, you just say the word. Thanks for maintaining this beast, much appreciated.

**Pull request merged**
