### PR TITLE
Add GCloud parameters as kwargs for storage.url

### PR DESCRIPTION
**Pull request by fao89**
It enables using kwargs, such as `content_type` https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_generate_signed_url

Ref: https://github.com/jschneier/django-storages/pull/1071

### CODE REVIEW

**Comment by ipanova** [comment]
@jschneier PTAL

**Review by ipanova — APPROVED** [review]
looks right to me! thanks!

**Comment by jschneier** [comment]
This looks generally fine, it doesn't allow people to override `expiration`, `version` or sometimes `bucket_bound_hostname`, can you update to fix that? I think the last one is okay but the first two should be override-able.

**Comment by fao89** [comment]
> This looks generally fine, it doesn't allow people to override `expiration`, `version` or sometimes `bucket_bound_hostname`, can you update to fix that? I think the last one is okay but the first two should be override-able.

@jschneier I've addressed your comment, could you please take another look?

**Comment by jschneier** [comment]
Looks good, thanks.

**Comment by fao89** [comment]
@jschneier do you have an idea when it will be released?

**Comment by ipanova** [comment]
@jschneier PTAL https://github.com/jschneier/django-storages/pull/1193#issuecomment-1309251640

**Pull request merged**
