### PR TITLE
Add neccessary steps for azure backend installation

### PR DESCRIPTION
**Pull request by aleccool213**
Add necessary steps for azure backend installation

Corresponds to https://github.com/jschneier/django-storages/issues/219

### CODE REVIEW

**Comment by alexjgraham** [comment]
+1

**Comment by mokutsu** [comment]
+1 👍

**Comment by ZuluPro** [comment]
@aleccool213  Thank you very much.

**Comment by k0nG** [comment]
The master version of the azure backend doesn't currently work with the Azure Storage. I've found setting my `azure` requirement to `1.0.3` fixes that.

**Pull request merged**
