### PR TITLE
Support all blobstorage settings

### LINKED ISSUE #643: custom domain for azure
Looking at the sdk it does look like the functionality does exist to be able to provide a custom domain but I don't see it in Django-Storages.

Reason why I need this is I have a site where I have a download link to some audio files that are stored on azure but browsers don't automatically download something that is not on the same domain

Am I missing something or is it not available?

### PR DESCRIPTION
**Pull request by nitely**
fixes #643

Changes:

- Add support for all blostorage settings
- Update docs

> AZURE_CUSTOM_DOMAIN is important to fetch azurite from a linked container

### CODE REVIEW

**Comment by TheArtOfPour** [comment]
Great changes! Can you explain how to configure the CDN url with these new variables?

**Comment by nitely** [comment]
Yeah, use the custom_domain setting for that. Here are the docs https://docs.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name

**Comment by malderete** [comment]
We should merge this PR. It improves the integration with Azure library's service.

**Comment by jschneier** [comment]
Hi this looks okay. My only question is about the required azure library bump, are there breaking changes from 3 to 4?

**Comment by nitely** [comment]
> My only question is about the required azure library bump, are there breaking changes from 3 to 4?

I double checked, all settings are there[0], so the version bump is not required. I temporarily pinned the version and all tests pass as well.

Not sure why I bumped them, maybe the changes did not in `CloudStorageAccount` or I had an old azure version :man_shrugging: 

[0] https://github.com/Azure/azure-storage-python/blob/v1.3.1-blob/azure-storage-blob/azure/storage/blob/blockblobservice.py#L96

**Comment by davidfischer** [comment]
Firstly, this is great work.

I'm having some trouble getting this to work with an Azure CDN setup as opposed to a blob service custom domain. From what I can tell when I turned up debugging, it looks like the custom domain is used as an API endpoint.

However, when used with Azure CDN, the custom domain resolves to `BUCKETNAME.azureedge.net.` rather than `BUCKETNAME.blob.core.windows.net` and then the API calls seem to fail.

Am I misunderstanding what the `custom_domain` setting is supposed to do? Should it work with a CDN setup?

**Comment by nitely** [comment]
Interesting. No, it won't work, because as you said, it will try to upload the file to the custom domain (cdn) and fail. I think we should add two internal services, one to generate the URLs using the custom_domain (cdn) and another one to upload/download through blob.core. I've to try whether that plays nice with the endpoint_suffix, though. I'll try it tomorrow and ping you so you can try it as well @davidfischer

**Comment by nitely** [comment]
I made some changes and this has worked for me:

* create a new file
* read the new file
* access the new file with through CDN (using the `file.url` property)

Can you give this a try @davidfischer

**Comment by davidfischer** [comment]
The changes worked for me. I tried:

- listing directories
- testing whether files exist
- getting the URL of a file (using `storage.url('path/to/file')`) - the custom domain was used in this case

**Comment by Maxyme** [comment]
Hi, what is the progress on this? This is really useful for using Azurite inside of docker-compose and setting the AZURE_CUSTOM_DOMAIN to point to that container.
Thank you for this PR.

**Comment by akshaybabloo** [comment]
Any update on this?

**Comment by nitely** [comment]
It's up to @jschneier to merge it. I'm guessing he's waiting for the next minor (v1.8) release. We have been using this for a few months now and it has worked well so far.

**Comment by jschneier** [comment]
Ugh I screwed up resolving the conflict in the GUI and now am not sure how to undo it.

**Comment by jschneier** [comment]
Moved this to #750. Sorry for that and thanks again @nitely. Would you be interested in helping to maintain the Azure backend?

**Pull request closed without merging**
