### PR TITLE
Pin dependency of azure storage blob to revert breakage by version 12

### PR DESCRIPTION
**Pull request by larserikgk**
This is a temporary fix for #784

### CODE REVIEW

**Comment by rik** [comment]
Latest version before 12.0.0 is 2.1.0. I'd suggest using a range rather than a strict version.

**Comment by larserikgk** [comment]
Fair point @rik. I pinned to 1.3.1 since that is what the `azure` module wants, but I agree with you.

**Comment by dmpe** [comment]
@jschneier can you please take a look on this ?
thanks

**Comment by jschneier** [comment]
Thanks.

**Pull request merged**
