### PR TITLE
PEP 621: Migrate from setup.py and setup.cfg to pyproject.toml

### PR DESCRIPTION
**Pull request by cclauss**
Migrate `setup.cfg` to `pyproject.toml` using [ini2toml](https://pypi.org/project/ini2toml) to do the file conversion and running [pyproject-fmt](https://pypi.org/project/pyproject-fmt) and then [validate-pyproject](https://github.com/abravalheri/validate-pyproject) to validate the results.

### CODE REVIEW

**Comment by jschneier** [comment]
This will need to be rebased now that the `ruff` changes are in. @cclauss would you also be interested in adding `black`?

**Comment by cclauss** [comment]
Rebased.  Let's do black in a separate PR after this lands because that might touch a lot of files

**Comment by jschneier** [comment]
Should this remove `ruff.toml` as well?

**Comment by cclauss** [comment]
> Should this remove `ruff.toml` as well?

Yes.  Much better, thanks.

**Pull request merged**
