### PR TITLE
Add support for AWS_SESSION_TOKEN and AWS_SECURITY_TOKEN

### PR DESCRIPTION
**Pull request by bxm156**
Add support for reading the AWS_SESSION_TOKEN and AWS_SECURITY_TOKEN from the environment.

Verified this works as expected in AWS Lambda.

### CODE REVIEW

**Comment by bxm156** [comment]
A few questions:

1) Should this be behind a setting ?
2) Should we care if the there is a AWS_SESSION_TOKEN but no AWS_ACCESS/SECRET keys in the env?

**Comment by AusIV** [comment]
I just encountered the same issue, and was glad to see someone had already done the legwork. I've also verified that this solves my problem on Lambda.

**Comment by narfman0** [comment]
I've verified this in my project as well, thanks Bryan! Should fix #282 too.

**Comment by jschneier** [comment]
Looks good!

**Comment by jschneier** [comment]
@bxm156 re: your questions. The docs are overdue for an overhaul. Authentication should be given its own section. I think relying on just the environment variables is likely better in this case but I need to read the aws docs again just to make sure.

**Comment by jschneier** [comment]
Oof. This only sets `.security_token` if it exists. I need to switch to live tests because you always try to reference the parameter even if it isn't getting set.

**Comment by bxm156** [comment]
Ah, sorry about that, I was planning on writing some tests for this but never got around to it :(

**Pull request merged**
