### PR TITLE
Add 'AWS4-HMAC-SHA256 signatures' section for Amazon S3

### PR DESCRIPTION
**Pull request by ad-m**
No extra comments required. 

I am not native speak, so please check English especially.

Thank @sdeleeuw for works in #28 and @mbarrien for prepare alternative backend.

### CODE REVIEW

**Comment by jschneier** [comment]
Thanks for this contribution. I'll need to improve the English a bit but it's very valuable information.

**Comment by ad-m** [comment]
Do you need any additional information?

**Comment by jleclanche** [comment]
Why not set default AWS_SIGNATURE_VERSION to s3v4? there is no harm doing so.

**Comment by ad-m** [comment]
@jleclanche , not all S3  non-Amazon servers such as Ceph Object Gateway support s3v4.

**Comment by jleclanche** [comment]
Okay sure, that's why we have the setting -- but the default should imho still look at aws s3 as the first class citizen.

The default behaviour being broken in some AWS regions is worse than the default behaviour being broken for some non-aws servers.

**Comment by jleclanche** [comment]
On top of this, looking at the [changes in v4](https://docs.aws.amazon.com/general/latest/gr/sigv4_changes.html), it sounds a lot more secure than v2 ... not including the key in the request is a big deal. Much saner default.

**Comment by jschneier** [comment]
We now have some language and I have opened #335 to default this.

**Pull request closed without merging**
