### PR TITLE
fixes issue:1216

### PR DESCRIPTION
**Pull request by santhosh-reddy03**
Please review the changes related to this issue, I have only updated the changes related to url functionality in AzureStorage.
I have tested by importing the module into my django application, haven't used test cases as they were not using connection_string.

Please let me know if they are any improvements/changes required.

### CODE REVIEW

**Comment by santhosh-reddy03** [comment]
I have updated the isort changes and pushed again.

**Comment by jschneier** [comment]
Thanks for the PR. This would definitely fix the issue (a test is missing though).

More generally: is there a use case for setting `AZURE_ACCOUNT_NAME` & `AZURE_ACCOUNT_KEY` if you are already setting `AZURE_CONNECTION_STRING`? If not, then probably it makes sense to parse these variables out in the constructor rather than in the `url()` method.

Maybe @alibeyram can weigh in?

**Comment by santhosh-reddy03** [comment]
When I was reproducing the issue, it was showing `account_key` was missing, but since we are able to set both `account_name` and `account_key` from connection_string, I m updating both.

@jschneier I have now updated the changes inside `__init__` function, Please check.

**Comment by jschneier** [comment]
@santhosh-reddy03 the indentation is wrong causing the lint tests to fail. Can you please fix.

**Comment by jschneier** [comment]
@santhosh-reddy03 failed again due to trailing whitespace.

**Comment by jschneier** [comment]
Merged, thanks.

**Comment by jschneier** [comment]
@santhosh-reddy03 where did the regex you used come from btw? the one in the issue is different. did you try generating connection strings with various characters?

**Comment by santhosh-reddy03** [comment]
No, for storage `account_name`, its alpha numerical's and for `account_key` they have not provided any specifications so I was considering all the characters till the next separation `;`. Will deep dive and see if there are any specifications or format for account_keys.

**Comment by santhosh-reddy03** [comment]
We can also use `find` method, if there are any issues with regex `string[string.find('AccountName'): string.find(';', string.find('AccountName'))].replace("AccountName=", '')`

**Pull request merged**
