### PR TITLE
S3Boto3Storage: fix for file-like objects without name, multipart upload support

### PR DESCRIPTION
**Pull request by pacahon**
In fact, it's partially solves problem. If we pass subclass of `File` class and forgot override `__bool__` method - an error based on empty name still can occur.

### CODE REVIEW

**Comment by linuxlewis** [comment]
👍 on seeing the SHA error. We've worked around it by ensuring we pass a `django.core.files.base.File` object with `name` defined.

**Comment by pacahon** [comment]
@linuxlewis Hi, can you show me where it's already fixed?

**Comment by linuxlewis** [comment]
@pacahon The "fix" is just a workaround in our code. We do something like this...

```python

from cStringIO import StringIO

from django.core.files.storage import default_storage
from django.core.files.base import File

default_storage.save('filename.txt', File(StringIO('content'), name='filename.txt'))
```

**Comment by pacahon** [comment]
@linuxlewis Thanks, that was my first thought. But `Storage` class accepts any file-object, so I'm looking for solution. Of course, my PR in its current state is just another workaround.

**Comment by pacahon** [comment]
Should check if already was documented that `upload_fileobj` waits for `bytes` or `seekable file object` in binary mode (the same as old `put` method)

**Comment by jleclanche** [comment]
PR needs rebasing but looks good to merge. @jschneier

**Comment by jschneier** [comment]
Updated and will be applied in #368. Thanks for the report and patch. Apologies for the delay.

**Pull request closed without merging**
