### PR TITLE
fix FTP LIST command output handling and add FTPStorageFile.name

### PR DESCRIPTION
**Pull request by skirsdeda**
Apparently current ftp backend implementation doesn't handle filenames with whitespace :D

### CODE REVIEW

**Comment by skirsdeda** [comment]
Also added name property to SFTPStorageFile and made SFTPStorage.__init__ a little bit more friendly

**Comment by skirsdeda** [comment]
LIST command handling should be good now. One thing I discovered about python's ftplib: it's no good with unicode! It's basically impossible to decode filenames properly even if server does it correctly because ftplib does encoding/decoding with default ANSI charset in python 3 so any unicode strings get sent/are received already garbled. Some warning along those lines could be added to the documentation I guess.

**Comment by sww314** [comment]
Closing stale requests.

**Comment by skirsdeda** [comment]
@sww314 That's very nice :) So nobody pays any attention to PR, nobody comments on it. Then it becomes stale and gets closed. I thought only defunct projects do that but whatever.

**Comment by sww314** [comment]
@skirsdeda the pull request is 3 years out of date and does not merge. Please feel free to update it. If it is important to you, then update it and request someone review. There are many open issues and VOLUNTEERS reviewing the code. 
Personally, I never use the ftp backend, so I have not idea if it works.

**Pull request closed without merging**
