### PR TITLE
Added AWS_EXTRA_HEADERS option

### PR DESCRIPTION
**Pull request by darkowic**
We found it useful to add special headers for files from specific path (e.g. user avatars)
I added AWS_EXTRA_HEADERS and created get_headers method for S3BotoStorage

### CODE REVIEW

**Comment by darkowic** [comment]
Will resolve conflicts soon.
Also there is one problem - this only works with save and not with write method so I have to find solution for this.
@jschneier what do you think about this feature?

**Comment by darkowic** [comment]
hey @jschneier ! I see that you are checking recently on this project.  I will have time to fix this feature and implement it for boto3. What do you think about it?

**Comment by jleclanche** [comment]
@darkowic I got commit access -- I'll take you up on the offer for reimplementing this for the s3boto3 storage instead; ping me once you do and I can review it!

**Comment by darkowic** [comment]
@jleclanche there is another idea for it
https://github.com/jschneier/django-storages/issues/231

What do you think? Btw I have to admit that I don't have much time recently to do this but maybe someone from my company can take care of it. We just need to decide how we want to implement it.

**Comment by sww314** [comment]
Closing in favor or #231

**Pull request closed without merging**
