### PR TITLE
Update s3boto.py - adding bucket_alias

### PR DESCRIPTION
**Pull request by nlundquist**
Adding bucket_alias kwarg to workaround inflexibility of explicit kwargs serialization in Django 1.7. Work towards resolving #22

### CODE REVIEW

**Comment by nlundquist** [comment]
This appears to be passing now on Travis CI? I think the failure was due to Travis environment setup issues with the tox dependency?

Anyhow I looked at the tests for the project and I didn't see anywhere the bucket kwarg is actually tested.It just tests the functions that depend on the bucket_name class var that is set by bucket & bucket_alias, so there isn't any obvious place to expand test coverage due to this change.

**Comment by nlundquist** [comment]
Is there something you're looking for before you approve this pull request?

**Comment by jleclanche** [comment]
@jschneier with the s3boto3 backend being around now i guess this wont get merged. close?

**Comment by jleclanche** [comment]
Closing per previous comment.

**Pull request closed without merging**
