### PR TITLE
[s3] Add support for signing CloudFront URLs

### LINKED ISSUE #456: Public and private objects on S3 via Cloudfront?
The django-storages docs just say I should set the `AWS_S3_CUSTOM_DOMAIN` setting and configure Cloudfront. The Cloudfront docs say I can restrict access and require signed URLs.

I already use signed S3 URLs with django-storages, and these URLs have `Expires`, `Signature` and `AWSAccessKeyId` querystring params. The Cloudfront docs say signed cloudfront URLs need `Expires`, `Signature` and `Key-Pair-Id` querystring params.

How can I get `django-storages` to generate a signed Cloudfront URL? Is it even possible?

### PR DESCRIPTION
**Pull request by terencehonles**
Fixes #456. Similar to #484 but uses AWS CloudFront signed URLS ([See AWS docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html))

This is probably the right way to approach the problem in #484, but if that solution works that might be an alternative (not sure how @mattjegan configured S3+CloundFront)

### CODE REVIEW

**Comment by jschneier** [comment]
Why even deal with multiple possible keys via ``AWS_CLOUDFRONT_KEYS``?

**Comment by terencehonles** [comment]
The warning or having multiple keys? I put it that way so you can have the key definition in one place (your settings.py), but have multiple storages which reference different buckets or different accounts (you may be allowed to sign CloudFront URLs for a different project if they have delegated permissions).

Either way there needs to be a `("key_id", "key")` tuple and I figured rather than store it as a list or two different settings it was more useful to just store it in a `dict`

**Comment by terencehonles** [comment]
Friendly reminder

**Comment by terencehonles** [comment]
Ping

**Comment by terencehonles** [comment]
@jschneier anymore thoughts about this PR?

**Comment by alexandernst** [comment]
Any news about this?

**Comment by dangelsaurus** [comment]
I'd love to see this soon!

**Comment by ericovis** [comment]
I was about to implement that myself, any news on this PR?

**Comment by thefedoration** [comment]
+1

**Comment by terencehonles** [comment]
For those that need this now you can install via an editable install in your requirements.txt w/ the following `-e git+git://github.com/<username>/django-storages.git@support-signing-cloudfront-urls#egg=django-storages`, you can use `terencehonles` as the username, but that will break when/if this PR gets merged and I delete the branch. You can clone my branch and reference your own repo, but the downside of any of an editable install is the package will pinned to this version unless you or I integrate any new changes from this repo.

**Comment by studybuffalo** [comment]
One other option that builds off the solution by @terencehonles: You can extended the `S3Boto3Storage` class and override the `url` method with the code in the pull request. You can then point the Django settings `DEFAULT_FILE_STORAGE` attribute to the custom class. This should work around the issues of pinning to the forked version.

**Comment by cobyrne09** [comment]
Does this repo have an active maintainer?

**Comment by jschneier** [comment]
It depends on how you define active I suppose. It comes in bursts for me
anyway. I do intend to look more at this one, sure.

**Comment by jschneier** [comment]
Hi, this looks okay. I'd rather we just do a single `AWS_CLOUDFRONT_KEY` and people can subclass as they wish. Can you update to that & rebase at which point we can merge?

**Comment by terencehonles** [comment]
@jschneier yeah I'll update this PR, I was doing my normal updating forks, but w/o looking at this PR when updating last.

**Comment by DataGreed** [comment]
@terencehonles So, how do I make cloudfront signing work? What do I have to specify in settings and how do I get the url?

**Comment by DataGreed** [comment]
@jschneier could you please release this version to PIP so it can be used in projects as dependency?

**Comment by DataGreed** [comment]
@terencehonles what exactly should be supplied for AWS_CLOUDFRONT_KEY? Should it be a path to some kind of pem file or some secret key? Either way I get `from_buffer() cannot return the address of a unicode object`

```

File "/project/.env/lib/python3.7/site-packages/storages/backends/s3boto3.py" in get_default_settings
  369.             cloudfront_signer = self.get_cloudfront_signer(cloudfront_key_id, cloudfront_key)

File "/project/.env/lib/python3.7/site-packages/storages/backends/s3boto3.py" in get_cloudfront_signer
  357.         return _cloud_front_signer_from_pem(key_id, key)

File "/project/.env/lib/python3.7/site-packages/storages/backends/s3boto3.py" in _cloud_front_signer_from_pem
  54.             pem, password=None, backend=default_backend())

File "/project/.env/lib/python3.7/site-packages/cryptography/hazmat/primitives/serialization/base.py" in load_pem_private_key
  16.     return backend.load_pem_private_key(data, password)

File "/project/.env/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py" in load_pem_private_key
  1089.             password,

File "/project/.env/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py" in _load_key
  1282.         mem_bio = self._bytes_to_bio(data)

File "/project/.env/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py" in _bytes_to_bio
  473.         data_ptr = self._ffi.from_buffer(data)

Exception Type: TypeError at /objects/3/
Exception Value: from_buffer() cannot return the address of a unicode object
```

**Comment by DataGreed** [comment]
Okay, I guess something like this works:

```
with open(os.path.join(BASE_DIR, "certs/aws-listenable.pem")) as aws_cert:
    AWS_CLOUDFRONT_KEY = aws_cert.read().encode('ascii')
```

**Comment by terencehonles** [comment]
@DataGreed glad you figured it out, I guess I probably should have seen if there was documentation I could have added to. Did you want to open a PR to potentially add your suggestion?

> ```
> with open(os.path.join(BASE_DIR, "keyfile.pem")) as aws_cert:
>     AWS_CLOUDFRONT_KEY = aws_cert.read().encode('ascii')
> ```

My keyfile is inline (actually a ENV VAR) instead of read via a file like your example, but I think what you wrote would get the point across. One comment is you can open your file in binary mode and you will get bytes and not have to `.encode('ascii')`

So:

```python
with open(os.path.join(BASE_DIR, "keyfile.pem"), 'rb') as cert:
    AWS_CLOUDFRONT_KEY = cert.read()
```

**Comment by DataGreed** [comment]
@terencehonles oh thanks! That makes more sense. Sure, I can try extend the docs if you won't be able to do it. 

@terencehonles btw, is there any way to change the expiration time?

**Comment by Faisal-Manzer** [comment]
When will the patch version be published with the official package?

**Comment by terencehonles** [comment]
> @terencehonles oh thanks! That makes more sense. Sure, I can try extend the docs if you won't be able to do it.

I _might_ be able to get to it, but I'm encouraging you to also contribute to the project just like I did :wink: 

> @terencehonles btw, is there any way to change the expiration time?

@DataGreed the expiration will be defined by the value you pass to the storage `url` function, if that isn't specified it defaults to `AWS_QUERYSTRING_EXPIRE`.

**Comment by SkiFamily** [comment]
Hi, 

Has anybody got this to work ? I will extend the docs to helpfully save other peoples time once I manage to get the CloudFront signing working but at the moment I can't seem to get it going. 

### My Process:

1. Removed django-storages
2. Installed django-storages from source (installed directly from the master branch with pip)
3. modified my `settings.py` to include:
```
    AWS_CLOUDFRONT_KEY = os.environ.get('AWS_CLOUDFRONT_KEY', None)
    AWS_CLOUDFRONT_KEY_ID = os.environ.get('AWS_CLOUDFRONT_KEY_ID', None)
```
4. Generated a CloudFront Key Pair as specified in [the docs]( https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-creating-cloudfront-key-pairs-procedure)
5. Updated my ENV vars with the corresponding values: 
AWS_CLOUDFRONT_KEY=-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
AWS_CLOUDFRONT_KEY_ID=APK....

The Key file is inline as specified by @terencehonles  but I still seem to get the buffer error @DataGreed mentioned 

I'll keep playing around with i, but could anybody point me in the right direction ? 

Here is the full error stack
```

Environment:


Request Method: GET
Request URL: https://skifamily-stage-pr161.osc-fr1.scalingo.io/

Django Version: 3.0.6
Python Version: 3.6.10
Installed Applications:
['allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'apps.SkiFamily.apps.SkiFamilyConfig',
 'apps.LeChalet.apps.LechaletConfig',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'oscar',
 'oscar.apps.analytics',
 'oscar.apps.checkout',
 'oscar.apps.address',
 'oscar.apps.shipping',
 'oscar.apps.catalogue',
 'oscar.apps.catalogue.reviews',
 'oscar.apps.partner',
 'oscar.apps.basket',
 'oscar.apps.payment',
 'oscar.apps.offer',
 'oscar.apps.order',
 'apps.OscarCustoms.customer',
 'oscar.apps.search',
 'oscar.apps.voucher',
 'oscar.apps.wishlists',
 'oscar.apps.dashboard',
 'oscar.apps.dashboard.reports',
 'oscar.apps.dashboard.users',
 'oscar.apps.dashboard.orders',
 'oscar.apps.dashboard.catalogue',
 'oscar.apps.dashboard.offers',
 'oscar.apps.dashboard.partners',
 'oscar.apps.dashboard.pages',
 'oscar.apps.dashboard.ranges',
 'oscar.apps.dashboard.reviews',
 'oscar.apps.dashboard.vouchers',
 'oscar.apps.dashboard.communications',
 'oscar.apps.dashboard.shipping',
 'oscar.apps.communication.apps.CommunicationConfig',
 'widget_tweaks',
 'haystack',
 'treebeard',
 'sorl.thumbnail',
 'django_tables2',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.frontend_cache',
 'modelcluster',
 'taggit',
 'wagtailfontawesome',
 'wagtail_blocks',
 'rest_framework',
 'rest_framework.authtoken',
 'corsheaders',
 'drf_yasg',
 'oscarapi',
 'webpack_loader',
 'lockdown']
Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'honeybadger.contrib.DjangoHoneybadgerMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'oscar.apps.basket.middleware.BasketMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'wagtail.core.middleware.SiteMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'lockdown.middleware.LockdownMiddleware')


Template error:
In template /app/templates/LeChalet/tags/layer_top_layer.html, error at line 8
   from_buffer() cannot return the address of a unicode object
   1 : {% load static wagtailimages_tags %}
   2 : 
   3 : {% image layer_top_layer.top_layer_background_image original as my_image %}
   4 : 
   5 : 
   6 : <section class="top-layer-wrapper"
   7 :         {% if my_image %}
   8 :          style="background-image: url( {{ my_image.url }} );" class="background-size-contain"
   9 :         {% else %}
   10 :          style="background-image: url({% static 'images/background/homepage-with-mask.png' %});" class="background-color-"
   11 :         {% endif %}
   12 : >
   13 :     {% if layer_top_layer.top_layer_mask %}
   14 :         <div id="background-mask"></div>
   15 :     {% endif %}
   16 : </section>
   17 : 
   18 : <div class="top_layer_spacer container">


Traceback (most recent call last):
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]

During handling of the above exception ('Rendition' object is not subscriptable), another exception occurred:
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 986, in render
    output = self.filter_expression.resolve(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/template/base.py", line 836, in _resolve_lookup
    current = getattr(current, bit)
  File "/app/.scalingo/python/lib/python3.6/site-packages/wagtail/images/models.py", line 505, in url
    return self.file.url
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/db/models/fields/files.py", line 62, in url
    return self.storage.url(self.name)
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/app/.scalingo/python/lib/python3.6/site-packages/django/core/files/storage.py", line 364, in _setup
    self._wrapped = get_storage_class()()
  File "/app/.scalingo/src/django-storages/storages/backends/s3boto3.py", line 253, in __init__
    super().__init__(**settings)
  File "/app/.scalingo/src/django-storages/storages/base.py", line 7, in __init__
    default_settings = self.get_default_settings()
  File "/app/.scalingo/src/django-storages/storages/backends/s3boto3.py", line 289, in get_default_settings
    cloudfront_signer = self.get_cloudfront_signer(cloudfront_key_id, cloudfront_key)
  File "/app/.scalingo/src/django-storages/storages/backends/s3boto3.py", line 277, in get_cloudfront_signer
    return _cloud_front_signer_from_pem(key_id, key)
  File "/app/.scalingo/src/django-storages/storages/backends/s3boto3.py", line 44, in _cloud_front_signer_from_pem
    pem, password=None, backend=default_backend())
  File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1098, in load_pem_private_key
    password,
  File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1291, in _load_key
    mem_bio = self._bytes_to_bio(data)
  File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 482, in _bytes_to_bio
    data_ptr = self._ffi.from_buffer(data)

Exception Type: TypeError at /
Exception Value: from_buffer() cannot return the address of a unicode object
```

**Comment by DataGreed** [comment]
@terencehonles could you please tell me if there is any way to make the specific URL never expire? Should I just pass a ridiculously high timestamp or `None`?

**Comment by terencehonles** [comment]
@DataGreed `None` will not work, but it really depends on your use case.

I pointed to the AWS docs in the PR description, and you can see this section [Private Content Overview: Choosing Duration](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html#private-content-overview-choosing-duration). A long duration may work for you, but if not, you will not be able to use a "Canned Policy" and [you can see the differences here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html#private-content-choosing-canned-custom-policy). This PR only implements a "Canned Policy" and you would have to alter the storage in order to provide a custom policy. You may even want to go as far as trying to validate that it is a valid policy (or is at least valid JSON)

**Comment by DataGreed** [comment]
@terencehonles than you so much for giving a detailed answer.

I think the longer expiration date will work for me - some of the uploaded files are public (like images) and should be used in open graph tags which facebook caches for some unspecified amount of time and some private file links should be valid for just a day.

In my case I was trying to make public links valid for longer period of time so opengraph images won't suddenly break. I guess if it will allow me to set 100 years, I am all set :D

I did not find any limitation description in Amazon docs, but one of the articles you posted above says

> You can also distribute private content using a signed URL that is valid for a longer time, possibly for years.

I'll post a follow up telling if it was a success or not.

**Comment by jnovkovic** [comment]
@SkiFamily Hey man, how did you manage to go above equal (=) sign in env? I'm getting the same error as you, and not sure how to proceed. 

Thanks.

**Comment by DataGreed** [comment]
> I'll post a follow up telling if it was a success or not.

Forgot to follow up, my bad. It was a success – you can set 100 years as expiration time. 
I've ended up just setting different expiration timeouts for private content and for public content.

**Comment by kumar-student** [comment]
> Hi,
> 
> Has anybody got this to work ? I will extend the docs to hopefully save other peoples time once I manage to get the CloudFront signing working but at the moment I can't seem to get it going.
> 
> ### My Process:
> 1. Removed django-storages
> 2. Installed django-storages from source (installed directly from the master branch with pip)
> 3. modified my `settings.py` to include:
> 
> ```
>     AWS_CLOUDFRONT_KEY = os.environ.get('AWS_CLOUDFRONT_KEY', None)
>     AWS_CLOUDFRONT_KEY_ID = os.environ.get('AWS_CLOUDFRONT_KEY_ID', None)
> ```
> 
> 4. Generated a CloudFront Key Pair as specified in [the docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-creating-cloudfront-key-pairs-procedure)
> 5. Updated my ENV vars with the corresponding values:
> 
> ```
> AWS_CLOUDFRONT_KEY=-----BEGIN RSA PRIVATE KEY-----
> ...
> -----END RSA PRIVATE KEY-----
> AWS_CLOUDFRONT_KEY_ID=APK....
> ```
> 
> The Key file is inline as specified by @terencehonles but I still seem to get the buffer error @DataGreed mentioned
> 
> I'll keep playing around with it, and update this comment as I go.
> 
> ### EDIT 1
> I have added
> 
> ` AWS_CLOUDFRONT_KEY = os.environ.get('AWS_CLOUDFRONT_KEY', None).encode('ascii')`
> 
> Which fixes the buffer error but raises a new one:
> 
> ```
>   File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1324, in _load_key
>     self._handle_key_loading_error()
>   File "/app/.scalingo/python/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1382, in _handle_key_loading_error
>     raise ValueError("Could not deserialize key data.")
> 
> Exception Type: ValueError at /
> Exception Value: Could not deserialize key data.
> ```
> 
> ### EDIT 2:
> The value of the key in my ENV VAR was wrong because the key contained an equal sign and my ENV parser considered it as another ENV VAR. I have found a workaround to define the appropriate value un my ENV vars and everything seems to be working fine now.
> 
> I have made a PR to update the docs #900

> Hi @SkiFamily Could you please elaborate on the process of resolving ValueError and Could not deserialize key data? I have followed AWS and Django-storages documentation and configured CloudFront but couldn't succeed
> AWS_CLOUDFRONT_KEY = os.environ.get('AWS_CLOUDFRONT_KEY', None).encode('ascii')
> AWS_CLOUDFRONT_KEY_ID = os.environ.get('AWS_CLOUDFRONT_KEY_ID', None)
> or 
> AWS_CLOUDFRONT_KEY = os.environ.get('AWS_CLOUDFRONT_KEY', None)
> AWS_CLOUDFRONT_KEY_ID = os.environ.get('AWS_CLOUDFRONT_KEY_ID', None)

**Comment by StevenMapes** [comment]
I'm still struggling with the _Could not deserialize key data_ errors. 

I've tried putting the value of the key into my .env file which is read by python-decouple but that does not work.

I've then put the key name into another settings variable, AWS_CLOUDFRONT_KEY_PATH, and tried each of the following:

```
with open(os.path.join(BASE_DIR, AWS_CLOUDFRONT_KEY_PATH)) as aws_cert:
    AWS_CLOUDFRONT_KEY = aws_cert.read().encode("ascii")
```
```
with open(os.path.join(BASE_DIR, AWS_CLOUDFRONT_KEY_PATH)) as aws_cert:
    AWS_CLOUDFRONT_KEY = aws_cert.read()
```

```
with open(os.path.join(BASE_DIR, AWS_CLOUDFRONT_KEY_PATH), "r") as aws_cert:
    AWS_CLOUDFRONT_KEY = aws_cert.read().encode("ascii")
```

```
with open(os.path.join(BASE_DIR, AWS_CLOUDFRONT_KEY_PATH), "rb") as aws_cert:
    AWS_CLOUDFRONT_KEY = aws_cert.read()
```

None of these work either.

The private key was generated as per the AWS docs by using ```openssl genrsa -out private_key.pem 2048``` with the public key then being ```openssl rsa -pubout -in private_key.pem -out public_key.pem```

I'm also a little confused by what ```AWS_CLOUDFRONT_KEY_ID``` should be as the docs do not explain it. I'm assuming it should either the literally ID of the key group on AWS or the public key that you save on AWS

**Pull request merged**
