### PR TITLE
New settings GS_CACHE_CONTROL to define caching policy via the Cache-Control HTTP header

### PR DESCRIPTION
**Pull request by cerny-jan**
If you use gcloud as a storage in your django project you usually want to leverage browser caching and this will allow you to do that.

### CODE REVIEW

**Comment by sww314** [comment]
The default for this should be None (or no cache). 
The way it coded now it allows public caching of files which may not be what people intended.

**Comment by cerny-jan** [comment]
@sww314 fair point, I've updated it

**Comment by erikkn** [comment]
Is it possible to create different cache-control headers for different type of files?

**Comment by jschneier** [comment]
Not sure why #505 didn't end up pushing here (I was trying to force push the rebase here). @erikkn that sounds like #231, I would take a PR for that.

**Pull request closed without merging**
