### PR TITLE
Truncate SpooledTemporaryFile after flushing the buffer

### PR DESCRIPTION
**Pull request by jiinus**
When uploading a file in chunks with S3BotoStorageFile I noticed that the underlying SpooledTemporaryFile is never truncated but instead successive write-calls just keep appending the file. 

With each flush the file is seeked to the beginning though which results in malformed data on S3 as the contents of the previous flushes are uploaded again and again on each write.

Also added the missing S3.py. License seems to permit it?

### CODE REVIEW

**Comment by jiinus** [comment]
This should also fix the problem mentioned in issue #160

**Comment by jschneier** [comment]
Thanks to you and @iceseyes for bringing this issue up. I'm going to write a failing test with a 5MB file and get this one fixed asap, probably with your fix.

I intentionally removed the S3.py file because it was deprecated in the original repo and I wanted to reduce my own maintenance burden, especially of already deprecated pieces of the library. New fork yadda yadda.

**Comment by m-barthelemy** [comment]
Hi there,

This is affecting us badly as well (from a 45MB file we end up with >15GB on S3 before Django give up).
Is there anything that could be done to help getting this fixed?

Thanks!

**Comment by todofixthis** [comment]
Possibly related:
- https://github.com/jschneier/django-storages/commit/5e14712e3532ae676bd207f213cc8e4bfcaa7a3b
- https://github.com/jschneier/django-storages/pull/106

**Comment by danpalmer** [comment]
Hi, ping on this? We have just encountered an issue where uploading ~10MB of data resulted in ~20GB of data being written to S3 - it _looks_ like this PR is the fix we need. Any possibility of a merge?

**Pull request closed without merging**
