### PR TITLE
Bugfix gs connection

### PR DESCRIPTION
**Pull request by patgmiller**
The `S3BotoStorage` class is overriding connection variables, this causes subclasses to use  `s3.amazonaws.com` as the host connection and fail authentication. 

Also reordered `Storage` class so it finds the overridden `get_available_name` instead of the one for super class.

### CODE REVIEW

**Comment by patgmiller** [comment]
@jschneier have you looked at this yet? Is there anything you would like me to do in order to get it accepted?

**Comment by jschneier** [comment]
Hi @patgmiller I understand the issue but this fix doesn't seem to actually use many of the `AWS_*` settings anymore, thus shattering backwards compat. Maybe what we need is to override the `@property connection`.

**Comment by patgmiller** [comment]
@jschneier would you then prefer something more like this?

```python
@deconstructible
class GoogleStorage(S3BotoStorage): 

    @property
    def connection(self):
        if self._connection is None:
            self._connection = self.connection_class(
                self.access_key, self.secret_key,
                calling_format=self.calling_format,
            )
        return self._connection
```

**Comment by dcgoss** [comment]
@patgmiller @jschneier I opened issue #124 not realizing it was a duplicate of this issue. My PR #125 should resolve the problem, in only one line.

**Comment by jschneier** [comment]
Closed in favor of #125 (thanks both @dcgoss  and @patgmiller)

**Pull request closed without merging**
