### PR TITLE
Add Django 3.2 trove classifier

### PR DESCRIPTION
**Pull request by jschneier**

### CODE REVIEW

**Comment by amureki** [comment]
@jschneier hey Josh!
I was debugging some issue with one of the latest Django releases (3.2.1) and noticed that django-storages is not yet have Django 3.2+ support (CI). 

Seeing this PR issue - I wonder if those were some flaky problems with pip/wheel setup and recent cryptography releases.
I think, we might want to try to restart this build to see if it was resolved.

Is there anything I can assist you with to get this going? 
Many thanks for maintaining this project!

Best,
Rust

**Comment by adamzap** [comment]
@jschneier Any update on Django v3.2 support? Is there any way your users can help push it forward? Thanks!

**Comment by jschneier** [comment]
@adamzap CI needs to work, we're dead in the water without it.

**Comment by jschneier** [comment]
CI is fixed but tests are broken by latest Django changes.

**Comment by adamzap** [comment]
I want to help, but I'm having trouble getting a development environment running for this project. Do you have instructions somewhere?

**Comment by allanlewis** [comment]
@adamzap Try `tox -e py38-django32 --develop`, you should just need Python 3.8 and `tox` for that to work. `tox -a` will list the available test configurations.

It seems that tests are failing on Django 2.2 as well as 3.2 😕

**Comment by jschneier** [comment]
Annoyingly, CI is not running because Travis no longer supports open source in the same way.

**Comment by adamzap** [comment]
@jschneier Are you interested in switching to GitHub Actions?

**Comment by jschneier** [comment]
@adamzap yup

**Comment by mariajgrimaldi** [comment]
Hi there! @adamzap @jschneier can I help with this?

**Comment by jschneier** [comment]
Please do!

**Comment by mariajgrimaldi** [comment]
Hi there! @adamzap @jschneier

I opened this PR: https://github.com/jschneier/django-storages/pull/1051. Any suggestions are welcome!

**Pull request merged**
