### PR TITLE
Dropbox fix and improvement

### PR DESCRIPTION
**Pull request by ZuluPro**
Made some fix for compatibility with others backend.

### CODE REVIEW

**Comment by jschneier** [comment]
This looks good (especially not returning from `read`, yeesh), what's the logic behind removing the `BytesIO` call?

On a side note I went spelunking through the dropbox api client code and there is an incredible amount of abstraction over what is essentially a thin wrapper on urllib3. It gets a bit much I think.

**Comment by ZuluPro** [comment]
@jschneier:

>  what's the logic behind removing the BytesIO call?

Do not really remember why, but I tested manually it's works.

>  On a side note I went spelunking through the dropbox api client code and there is an incredible amount of abstraction over what is essentially a thin wrapper on urllib3. It gets a bit much I think.

I plan to add DropBox Driver to Libcloud, and in this lib all is made ± from raw. Would you prefer to use it in future ?

**Comment by ZuluPro** [comment]
Any news ?

**Comment by jschneier** [comment]
Thanks for staying on top of me on this.

**Pull request merged**
