### PR TITLE
Django 1.8+ compatibility

### PR DESCRIPTION
**Pull request by maryokhin**
As per the [deprecation note](https://docs.djangoproject.com/en/dev/releases/1.8/#support-for-the-max-length-argument-on-custom-storage-classes).

### CODE REVIEW

**Comment by jschneier** [comment]
Thanks for this it looks great! My only concern is whether the ``super`` calls with no arguments will work on Python2.

**Comment by maryokhin** [comment]
Yes, it should work because it is a [new style class](https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes) + the build would have failed otherwise.

**Comment by mbarrien** [comment]
Wrong, argumentless super() was introduced in Python 3, and never back ported. From a Python 2.7 REPL session:
```
>>> class Foo(object):
...     def func(self):
...         print "Foo"
...
>>> class Bar(Foo):
...     def func(self):
...         super().func()
...
>>> Bar().func()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in func
TypeError: super() takes at least 1 argument (0 given)
>>>
```

**Comment by maryokhin** [comment]
Ok, true. I don't use Python 2, didn't expect it to still be such a mess. I'll fix it.

**Pull request merged**
